### ISSUE TITLE
CCloud topic schemas don't load unless the Resources view loads environments

### ISSUE THREAD

**Issue by shouples** [confluentinc/vscode#147]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### VS Code version

1.93.0

### Version of Confluent extension

v0.15.0

### To Reproduce

Collapse the Resources view and connect to CCloud, then select a Kafka cluster in the Topics view; the topics will appear as schemaless

### Which area(s) are affected? (Select all that apply)

Topics, Schemas

**Comment by jlrobins** [comment]
Am working on this.
