### ISSUE TITLE
Respell resourceManager.setCCloudSchemaRegistryCluster() to take list of clusters in bulk.

### ISSUE THREAD

**Issue by jlrobins** [confluentinc/vscode#215]
Main callpoint for setCCloudSchemaRegistryCluster() is from preloadEnvironmentResources(), which could call with whole list of all of the ccloud schema registries.

Refactor to accept a list, then wholly resetting the stored value, and doing so just once, not for each schema registry found within that loop.

**Comment by shouples** [comment]
What arrays/lists of Schema Registry clusters are we expecting here? Or is this to specifically gather up each SR cluster across all available CCloud environments and add to extension state at once?

**Comment by jlrobins** [comment]
> What arrays/lists of Schema Registry clusters are we expecting here? Or is this to specifically gather up each SR cluster across all available CCloud environments and add to extension state at once?

The latter. We already know the whole set of them from the graphql response. Gather those up into a single array, pass to storage all at once instead of one at a time. Is a baby optimization, but spotted it while prepping the pre-caching work and didn't want to mix it in with that branch.
