### ISSUE TITLE
Topics should have quick action for loading latest schema version

### ISSUE THREAD

**Issue by shouples** [confluentinc/vscode#261]
It currently takes two levels of expanding to get to the schema versions themselves, and another to open the latest version:
<img width="429" alt="image" src="https://github.com/user-attachments/assets/6b40a508-fd6a-4c31-a019-5319053442ef">

Four clicks! 🙅

**Comment by shouples** [comment]
If this were to be labeled as something like `Open Latest Schema Version`, it could then also show an `Open Schema Version...` with a quickpick to show available versions.

**Comment by jlrobins** [comment]
@shouples : OK, can see how to hand new 'Open Latest Schema(s)' in the context menu based on context value matching `/.*kafka-topic.*with-schema.*/`

And then would open up either / both the latest key and value schema in at most two new schema views. 

Or do you think two separate menu entries based on either key or value schemas being present? I think starting with the single menu entry that will open up either one or two windows is good for first pass here.
