### ISSUE TITLE
Can not login via Confluent Cloud

### ISSUE THREAD

**Issue by Schiewatir** [confluentinc/vscode#262]
Type: <b>Bug</b>

I can't login to confluent cloud via this extension while we are ussing our organisation account, and always get an error Authentication Failed

Extension version: 0.16.3
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.8.0-1013-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 5650U with Radeon Graphics      (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.31GB (12.01GB free)|
|Process Argv|--crash-reporter-id 18d36f2a-dfc0-49d8-a2be-c3d119ac647c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.83.217.20|
|OS|Linux x64 6.8.0-1013-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 0)|
|Memory (System)|15.57GB (13.78GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563
iacca1:31138162
5fd0e150:31140164

```

</details>

**Comment by rohitsanj** [comment]
Hi @Schiewatir, thank you for reporting this issue. I'm an engineer on the team working on this VS Code extension and I'd be glad to help resolve this. 

It appears that you might have the extension installed and running in your local Windows host machine's VS Code workspace, as well as in the remote Linux instance's VS Code workspace, and they're not playing nicely with each other. Please note that we don't yet explicitly support using the Confluent extension from a Remote-SSH VS Code workspace.

As a workaround, could you please try the steps mentioned below and let me know if that fixes the login issue? Thanks in advance!

1. Uninstall the Confluent extension from your host Windows VS Code workspace. Make sure to leave the extension installed in the remote Linux VS Code workspace. (Go the the Extensions tab and you'll see two dropdowns -- one called "Local - Installed" and the other "SSH: <remote IP> - Installed", please uninstall Confluent from the "Local - Installed" list)
2. Close all VS Code workspaces and please wait 1-2 minutes for any lingering processes to exit cleanly
3. Re-open VS Code and login to your remote Linux server
4. Open the Confluent extension and try logging in to Confluent Cloud

From testing a similar configuration on my machine with a remote server, I've found that VS Code automatically forwards the port `26636` from the remote server to the same port number on the host. However, if you've followed the steps above and see a "This site cannot be reached" in your browser when trying to login to Confluent Cloud, this probably means that the port was not forwarded for some reason. In that case, please follow this [guide](https://code.visualstudio.com/docs/remote/ssh#_forwarding-a-port-creating-ssh-tunnel) to temporarily forward the port `26636` and try logging in again.

**Comment by Schiewatir** [comment]
Thank you, by adding the port the problem is solved.
