### ISSUE TITLE
Allow for configuration of local kafka resource attributes

### ISSUE THREAD

**Issue by MSeal** [confluentinc/vscode#267]
Currently we rely on port 8082 for a Kafka Rest Proxy endpoint to provide metadata about local Kafka clusters to enable connection.

Instead we should provide defaults that are configurable for when there's no Kafka Rest Proxy or when it's on a different port.

In building this we should consider future remote Kafka instances in a similar connection path.

**Comment by rohitsanj** [comment]
For Confluent Local, we'll always assume Kafka REST to be running on port 8082. For direct connections to local or remote Kafka clusters, we'll use the configured bootstrap servers as part of the connection configuration. Closing this ticket.
