### ISSUE TITLE
Add configurations for local Schema registry base URL + port

### ISSUE THREAD

**Issue by shouples** [confluentinc/vscode#275]
### User Stories 

**As a developer:**
1. I need to access the schemas & schema registry available on my local machine from the Schema Registry Panel
2. I need the Schema Registry Panel to show which schema registry I am currently viewing
3. I need to be able to to switch between CC schema registry and local schema registry quickly and easily
4. I need to be able to change the port/settings of my schema registry

### MVP Implementation Details

- Schema registry settings, including base URL & port, will be found and managed in a new section in the Confluent Extension Settings.
- Identifying details for the local schema registry should appear in the label of the Schemas Panel Header
- The user should be able to select between the local schema registry & available CC schema registries in the existing quick pick option (shown below)

<img width="628" alt="Screenshot 2024-10-10 at 2 35 50 PM" src="https://github.com/user-attachments/assets/3d6974ba-37ec-49c6-a9ad-54af3858c5d8">

### TBD Implementation Details

**Identifying Local Schema Registries**
Currently, the CC Schema Registry shows the Environment and Cluster in the label for the Schema registry header. What is the best identifying information for the local schema registry? Do we need to show the Connection type here or will the cluster + environment be sufficient for now?

### Future Considerations
This is an MVP experience for Local Schema Registry Support, but we will have to consider additional details and a more comprehensive work flow for Confluent Platform Support that may move the Local Settings selector out of the Extension Settings and embed them into the extension itself, but that is out of scope for this ticket. [Another ticket](https://github.com/confluentinc/vscode/issues/360) has been created to track those improvements.

**Comment by MSeal** [comment]
This work would primarily resolve if the managed docker image ports aren't available. For now we're assuming managed ports are and will return to this item if that turns out to be problematic often.
