### ISSUE TITLE
Pass local Kafka/SR configurations to sidecar on startup + settings change events

### ISSUE THREAD

**Issue by shouples** [confluentinc/vscode#276]
In order for the sidecar to properly discover the local Kafka & Schema Registry containers, it needs to know the REST proxy ports.

Currently, we're hard-coding the Kafka REST proxy port to `8082`, but the Schema Registry REST proxy port can be adjusted based on the `local_config` value of a sidecar [ConnectionSpec](https://github.com/confluentinc/ide-sidecar/blob/85520eb4e9558237c6979b0cb4156a30cdb04ee6/src/generated/resources/openapi.yaml#L635-L640).

This (SR) config will be adjustable by the user, but that means changing it with an existing (SR) container will require two things:
- making a `PUT` request to the (sidecar) connections API for the existing local connection
- prompting the user ask if they want to restart the existing local resources (via our Docker engine API integration)

Listening for the configuration change will be done the same way we handle watching for SSL config related changes: https://github.com/confluentinc/vscode/blob/main/src/preferences/updates.ts#L49

**Comment by MSeal** [comment]
This is instead being achieved through docker events

**Comment by shouples** [comment]
Reopening with an updated description since we'll need this extension settings sync to happen between the extension and the sidecar, as well as the extension and any local resources running in Docker.

**Comment by shouples** [comment]
Re-closing since we'll dynamically assign the SR REST port on startup instead of dealing with settings syncing.
