### ISSUE TITLE
SSO login fail with Confluent Cloud

### ISSUE THREAD

**Issue by Damien-Fayet** [confluentinc/vscode#280]
Type: <b>Bug</b>

Hello, when logging in with the SSO connection to my Confluent Cloud account, I have the following error message :
Authentication Failed

We couldn't complete the authentication with Confluent Cloud due to the following error:

Failed to create SSL connection

You may close this page and re-start the authentication flow in VS Code.

Extension version: 0.16.3
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 5, 5|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 7e9d894a-a5a9-447a-add8-f8bf8fd711cc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by flippingbits** [comment]
Thanks for reporting the issue, @akrewTik! Do you know if you're sitting behind a firewall that performs SSL inspection, in which case the firewall would re-encrypt the traffic with a (custom) certificate?

**Comment by akrewTik** [comment]
Yes, indeed, I am behind a PaloAlto instance that is doing SSL inspection. How can I add my own certificate to the plugin configuration ?

**Comment by flippingbits** [comment]
Thanks for confirming, @Damien-Fayet! We'll add support for custom certificates shortly. I expect it to land in the next few days. See also https://github.com/confluentinc/vscode/issues/268.

**Comment by flippingbits** [comment]
Duplicate of #268

**Comment by flippingbits** [comment]
@Damien-Fayet - We released extension version v0.17.0 yesterday that introduced two extension settings for working with custom SSL certificates (copied from the [changelog](https://github.com/confluentinc/vscode/blob/main/CHANGELOG.md)):
* Users can now **provide custom SSL certificates** in the extension settings (Confluent -> SSL -> Pem Paths) for authenticating with Confluent Cloud. This is useful for users whose machines are behind a corporate firewall or a VPC configuration that requires custom SSL certificates. Please note that automatic use of certificates from Trust Store to alleviate the need for custom SSL certificates is scheduled (https://github.com/confluentinc/ide-sidecar/issues/69 and https://github.com/confluentinc/ide-sidecar/issues/70).
* Added a new extension setting for **disabling SSL server certificate verification** on any HTTPS requests made by the extension. WARNING: Using this setting is not recommended as it may allow a Man-in-the-Middle attack. It should only be used to diagnose SSL problems or to temporarily work around a known certificate issue.

May I trouble you to give them a try?

**Comment by Damien-Fayet** [comment]
Hello,
I gave a try and updated the plugin (it's up to date with v0.17.1 and I can see in features the SSL Path): 
- I'm not able to find confluent.debugging.sslTls.serverCertificateVerificationDisabled nor confluent.ssl.pemPaths  in settings. I have only 2 available under confluent settings : "Show schema Warning Notifications" and "Show Sidecar Esceptions"
- I tried also the command "confluent.connections.addSSLPemPath" through command palette but I still have an error. (More explicit by the way, saying that my certificate could not be validated)

Sorry, perhaps I'm just missing where to find the extensions settings (I'm on MacOS).
Thanks !

**Comment by flippingbits** [comment]
Hey @Damien-Fayet - Thanks for getting back to me.

Can you try restarting VS Code? Your extension settings should look as follows:

<img width="975" alt="Screenshot 2024-10-04 at 14 07 51" src="https://github.com/user-attachments/assets/fc0557fb-6369-4f1f-8869-4923b49e4682">

You can reach the settings from the "detail page" of the extension:

<img width="1181" alt="Screenshot 2024-10-04 at 14 09 04" src="https://github.com/user-attachments/assets/736a1014-d72e-41f2-b246-2a6620a01860">

Let me know if this doesn't work for you.

**Comment by Damien-Fayet** [comment]
Indeed, it's working much better after a restart :)

Thanks
