### ISSUE TITLE
Keep getting logged out of confluent cloud

### ISSUE THREAD

**Issue by roberto-molinari** [confluentinc/vscode#281]
Type: <b>Bug</b>

After I successfully log in to Confluent Cloud and start doing work in the IDE, I get logged out and have to re-log in.

This may be the same behavior that we have in the Confluent Cloud UI bit its annoying to have to keep re-logging in. 

Would be a better experience if I can remain logged in for much longer.

Extension version: 0.16.3
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id a94e9292-2792-4272-bb61-f29756bd22e9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
autoexpandse:31133494
ei213698:31121563

```

</details>

**Comment by jlrobins** [comment]
Hi Roberto,

Yes, the CCloud backend can only give us a 4-hour token, the same as is given to the CCloud web UI. This is not currently configurable for any Confluent front-end at this time. We will reach out to the internal team to see if we can get a whole-workday token duration.

As the token is nearing expiration, you _should_ see prompts to re-authenticate. And it should only happen at around the 3h30m mark or so. If it happens earlier than that, or w/o any UI prompting, and independent of any explicit logout of the CCloud web UI in browser, then please let me know.

**Comment by derek1ee** [comment]
Happened to me and it was a surprise - thought it's a bug. I never saw the prompting, it's not in the notifications list - not sure if I missed it or if it's never shown.

Can the extension not automatically renew when it's near expiration?

**Comment by flippingbits** [comment]
> Can the extension not automatically renew when it's near expiration?

Our refresh tokens have an absolute lifetime of 4 hours after which users must re-authenticate with Confluent Cloud. We're trying to increase the token lifetime.

**Comment by roberto-molinari** [comment]
I just got logged out after ~20min

I did lock / unlock my laptop, in case that matters (would not expect it to)

**Comment by flippingbits** [comment]
Thanks for getting back to me, @roberto-molinari. This is **not** expected behavior. I'll check it with our identity team.

**Comment by flippingbits** [comment]
@roberto-molinari - We checked our OAuth setup but couldn't find anything suspicious.

I tried to reproduce your issue today and found out that [putting the laptop into sleep mode may cause early log-outs](https://github.com/confluentinc/vscode/issues/307). Given that locking the laptop might put it into sleep mode, your early log-out might have been caused by this bug. We'll try to fix the issue in one of our next releases.

In the meantime, please let me know if you experience similar behavior, i.e., early log-outs, despite not having locked your laptop.

FWIW, signing out from the CCloud UI will cause an early log-out, too.

**Comment by derek1ee** [comment]
I think I also experienced this. See my notification history, first the success log in message then failure, no reminder in between.

<img width="299" alt="Screenshot 2024-10-01 at 12 59 42 PM" src="https://github.com/user-attachments/assets/54914b34-1306-4944-b5e7-9c020d71ccbb">
<img width="560" alt="Screenshot 2024-10-01 at 12 59 53 PM" src="https://github.com/user-attachments/assets/f1626292-e492-4ce4-832b-e31d22f6a416">

**Comment by flippingbits** [comment]
@derek1ee Thanks for sharing these screenshots!

* Do you recall how long it took you to go from "Successfully logged in.." to "Error authenticating with ..."?
* Did you put your laptop into sleep mode in between or perform any other action that might affect the session, like signing out from the Confluent Cloud UI in your browser?

**Comment by shouples** [comment]
Based on updates to the extension and sidecar for our [0.20.0 release](https://github.com/confluentinc/vscode/releases/tag/v0.20.0) (which will be hitting the Marketplace later this morning), this should no longer be an issue. Let's reopen this if the issue reappears.
