### ISSUE TITLE
Change cluster via Topics explorer throws error the first time

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#282]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### On what operating system are you seeing the problem?

macOS (Apple/arm64)

### VS Code version

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

### Version of Confluent extension

v0.16.3

### To Reproduce

1. Install the extension and sign into CC
2. From "Resources", navigate to a cluster that has topic
3. Observe topics shows up under "Topics"
4. Click on "Select Kafka Cluster" on the "Topics" header

### Current vs. Expected behavior

Observe error message "Unknown cluster type" shown on the bottom right as pop up.
Observe the "Topics" tree switch to "No topics found. Create Topic" even though it still shows the previous cluster on the header

<img width="838" alt="Screenshot 2024-09-24 at 12 49 49 PM" src="https://github.com/user-attachments/assets/c1599ded-99b0-4f76-b4f5-572221fd9de7">

Click on "Select Kafka Cluster" again seem to resolve the issue and brought up the cluster selection dropdown.

Expected:
Click on "Select Kafka Cluster" works the first time to bring up the cluster selection dropdown.
Before cluster selection is changed, the "Topics" tree should remain showing the previously selected cluster's topics.

### Which area(s) are affected? (Select all that apply)

Confluent Cloud, Topics

**Comment by jlrobins** [comment]
Thanks for your report, Derek. We have a fix in progress.

**Comment by jlrobins** [comment]
Fix will be a part of the next release, 0.17.0, thanks!
