### ISSUE TITLE
Nit: Unavailable action should be hidden/disabled

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#283]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### On what operating system are you seeing the problem?

macOS (Apple/arm64)

### VS Code version

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

### Version of Confluent extension

v0.16.3

### To Reproduce

1. Sign in to CC
2. Try to rename environment (or topic)

### Current vs. Expected behavior

Observe "COMING SOON: Renaming environments is not yet supported"

The current behavior gives user the illusion of being able to rename, only after they've decided to take the action will they find out that it's not available. The pop up also shows up at bottom right which isn't what the user's attention is at so they may not even see it.

Alternatively, the button should be hidden or disabled (with tooltip explaining it's coming soon).

### Which area(s) are affected? (Select all that apply)

Confluent Cloud

**Comment by noeldevelops** [comment]
We have a path forward - if it's unsupported due to "coming soon", let's hide it. If it's unavailable due to RBAC/permissions, we'll disable and add a tooltip.
