### ISSUE TITLE
canAccessSchemaTypeForTopic() may get called with null

### ISSUE THREAD

**Issue by jlrobins** [confluentinc/vscode#289]
Callpath `activateMessageViewer()` -> `canAccessSchemaForTopic()` can somehow end up calling `canAccessSchemaForTopic` with null, which then raises an uncaught exception when trying to dereference `!topic.environmentId`.

**Comment by shouples** [comment]
Closing this since it should be handled in the next release based on the updates to expose Message Viewer from the command palette and guarding before we even get into `canAccessSchemaForTopic()`: https://github.com/confluentinc/vscode/blob/main/src/consume.ts#L35-L40
