### ISSUE TITLE
After pausing a topic message viewer, the "waiting for messages..." message presists

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#294]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### On what operating system are you seeing the problem?

macOS (Apple/arm64)

### VS Code version

Version: 1.93.1 (Universal)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 22.6.0

### Version of Confluent extension

v0.16.3

### To Reproduce

1. Install, sign in to CC, and navigate to a topic that doesn't get any new message
2. Click the play button to open message viewer
3. Observe "waiting for messages..." spinner shown
4. Click "Pause"
5. Observe the page

### Current vs. Expected behavior

Expected: The "waiting for messages..." text should probably change to something like "Resume to see messages"
Current: The "waiting for messages..." stays

<img width="866" alt="Screenshot 2024-09-24 at 4 35 44 PM" src="https://github.com/user-attachments/assets/eabe72f4-0cd9-422f-a03c-4f8497ca64f7">

### Which area(s) are affected? (Select all that apply)

Messages

**Comment by noeldevelops** [comment]
@alexeyraspopov has a WIP to fix this. Will get input on messaging from @derek1ee and @katehollowayconfluent
