### ISSUE TITLE
VS Extension does not discovering local Kafka 

### ISSUE THREAD

**Issue by shaharzi** [confluentinc/vscode#350]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### On what operating system are you seeing the problem?

Windows (x64)

### VS Code version

1.94.0

### Version of Confluent extension

0.17.1

### To Reproduce

1. install extension
2. execute docker with CP, broker, zookeeper and schema registry
3. restart VS Code
4. Open resource window of the extension
5. Noting shows but the button to connect to CC

### Current vs. Expected behavior

the extension does not auto discover the local confluent kafka located on Docker with docker compose

### Relevant log output

```shell
a
```

### Which area(s) are affected? (Select all that apply)

Not sure

**Comment by jlrobins** [comment]
Hi Shaharzi,

We're actively working towards Confluent Platform support this quarter, be it in local Docker or live CP. Stay tuned!

James

**Comment by shouples** [comment]
Hey @shaharzi - with our latest `0.22.x` release(s), we introduced a preview setting to allow connecting directly to a Kafka cluster or Schema Registry. Are you able to use that to connect to your local CP services?

To get started, first make sure the `confluent.preview.enableDirectConnections` setting is enabled:
<img width="922" alt="image" src="https://github.com/user-attachments/assets/05dbf17d-8173-4dee-b28d-73520d798022" />

Then you should see an "Other" item in the Resources view, with a ➕ icon that opens a connection form:
<img width="1588" alt="image" src="https://github.com/user-attachments/assets/5e4fbb54-e1dd-446d-8219-f49bb10b5efe" />


Discovering those (running locally in Docker) will take a bit longer to set up, but we have plans for more local Docker support in general that should help for your use-case as well.

**Comment by shaharzi** [comment]
hi @shouples ,

Yes ! it works . thank you for the quick solution and yes I'm able to connect to local CP services include Schema Registry. so well-done for you all.
