### ISSUE TITLE
Extension not loaded properly right after install

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#476]
1. On VS Code, ensure the extension is not installed.
2. Go to extension page, and install the extension.
3. Observe the Confluent extension logo shows up on left nav.
4. Click on the extension logo to open the extension.
5. Observe the extension is not properly loaded.
6. Close VS Code and reopen.
7. Observe the extension is now properly loaded.

Happens when installing from extension marketplace as well as sideloading .vsix.

<img width="1356" alt="Screenshot 2024-10-30 at 10 11 33 AM" src="https://github.com/user-attachments/assets/18eff8ef-fbd8-409e-ac2d-07fe98ce5c6d">

**Comment by shouples** [comment]
Thanks for filing this @derek1ee, I think there's definitely some deactivation-related cleanup we're missing since @Cerchie also saw odd behavior when updating in https://github.com/confluentinc/vscode/issues/520. Going to try and tackle these before our next release.
