### ISSUE TITLE
Use `window.setStatusBarMessage` for long-running view progress indicators

### ISSUE THREAD

**Issue by shouples** [confluentinc/vscode#495]
When the Docker event listener catches a supported (Kafka/SR) container starting, it shows a progress indicator in the Resources view. Unfortunately, no text is shown here indicating to the user what exactly is loading/happening. 

Separate from https://github.com/confluentinc/vscode/issues/444, we could show ephemeral status bar updates to indicate the Resources view is waiting on something (e.g. a Kafka container's logs to show the `Server started, listening for requests...` message), which would then clear as soon as the event listener resolves.

This should also include a `boolean` setting/configuration in package.json to disable/enable altogether.

**Comment by noeldevelops** [comment]
There are other UX options - @shouples to prototype

**Comment by shouples** [comment]
Not really applicable anymore since we're just using progress notifications
