### ISSUE TITLE
"Evolve Schema" action

### ISSUE THREAD

**Issue by jlrobins** [confluentinc/vscode#504]
Context menu action invoke-able on the latest schema version or the schema subject group to "Evolve Schema":
  * Downloads that schema document (if invoked on the subject group, then get the latest version).
  * Drops the contents into a new editable buffer, setting the file name of the buffer to be something like "draft-<subject>-<nextversion>.<avsc|proto|json>"
  * Use https://github.com/confluentinc/vscode/issues/503 to associate the document with the source schema registry, subject name.
 
User can then edit, then because is named right, will have the 'upload schema' action available to it.

Augment the upload schema action to consult https://github.com/confluentinc/vscode/issues/503 API to find the preferred schema registry + subject name to streamline the upload process.

**Comment by shouples** [comment]
Done in https://github.com/confluentinc/vscode/pull/714
