### ISSUE TITLE
Pem file not always utilized

### ISSUE THREAD

**Issue by xdgrulez** [confluentinc/vscode#523]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### VS Code version

1.95.1

### Version of Confluent extension

0.20.1

### To Reproduce

1. Add pem under "Confluent → Ssl → Pem Paths"
2. Login to Confluent Cloud
3. List clusters (OK)
4. List topics (doesn't work)
5. Enable "Confluent → Debugging → Ssl Tls → Server Certificate Verification Disabled"
6. List topics (OK)

### Current vs. Expected behavior

I expect "list topics" to work without having to go to "SSL insecure". I assume that the configured pem file is not utilized in the call for "listing topics" on a cluster (the clusters can be listed... so here the pem file is probably applied).

### Relevant log output

```shell
Step 4:

{"status":"500","code":"proxy_error","title":"Something went wrong while proxying request","id":"610ce537-478c-42a1-ad6e-f5801a8bb93b","errors":[{"code":"proxy_error","title":"Failed to create SSL connection","detail":"Failed to create SSL connection"}]}
```

### Which area(s) are affected? (Select all that apply)

Topics

### Additional context

n/a

**Comment by flippingbits** [comment]
Thanks for reporting the issue, @xdgrulez! I'll take a look at it and get back to you as soon as possible.

**Comment by xdgrulez** [comment]
Hey @flippingbits, yes it does.

**Comment by flippingbits** [comment]
> Hey @flippingbits, yes it does.

Thanks a lot for confirming!

I have two follow-up questions:

1. Can you check if you can list clusters using the default settings (no PEM file, cert verification enabled)?
2. Could it be the case that you need to use a different PEM file for accessing the private cluster's REST endpoints? To give you context, we interact with the control plane of Confluent Cloud for [listing clusters](https://docs.confluent.io/cloud/current/api.html#tag/Clusters-(cmkv2)/operation/listCmkV2Clusters) (hostname: `api.confluent.cloud`), and interact with the data plane of Confluent Cloud for [listing topics](https://docs.confluent.io/cloud/current/api.html#tag/Topic-(v3)/operation/listKafkaTopics) (hostname should match `$lkcId-$nid.$region.$cloud.glb.confluent.cloud` if you're using a private link to access the cluster). So these two operations might require different PEM files.

**Comment by xdgrulez** [comment]
Aha, I don't have my work laptop with me now, but I don't think that we need two different PEM files. What I guess is that we *do* need the PEM file for the connection to api.confluent.cloud (which is in public cloud), and we *do not* need a PEM file for the data plane (which is in private cloud). So maybe the problem is that the PEM file should *not* be used by the VSC plugin for connecting to the data plane. 

Would it be possible to have two separate PEM file configurations for the two connections, where we could configure the PEM file for the control plane REST calls and it would be possible to set another (or in our case, *no* PEM file) for the data plane REST calls?

**Comment by flippingbits** [comment]
Thanks for getting back to me. That's very helpful.

> What I guess is that we do need the PEM file for the connection to api.confluent.cloud (which is in public cloud), and we do not need a PEM file for the data plane (which is in private cloud). So maybe the problem is that the PEM file should not be used by the VSC plugin for connecting to the data plane.

We ship the VS Code extension with a few _baked-in_ certs that are used to verify server certs. When a PEM file is configured, we ignore the baked-in certs at the moment. Let me see if we can change that so that we also try the baked-in certs to verify the server cert of the data plane. Maybe this will fix your issues.

> Would it be possible to have two separate PEM file configurations for the two connections, where we could configure the PEM file for the control plane REST calls and it would be possible to set another (or in our case, no PEM file) for the data plane REST calls?

You can provide multiple PEM files to the extension at the same time. The extension considers all of them when verifying the server cert.

**Comment by xdgrulez** [comment]
Hi! I think your proposal could work:

> We ship the VS Code extension with a few baked-in certs that are used to verify server certs. When a PEM file is configured, we ignore the baked-in certs at the moment. Let me see if we can change that so that we also try the baked-in certs to verify the server cert of the data plane. Maybe this will fix your issues.

I can also try to add a "standard PEM" file to the list that in a way works like one of your baked in ones - maybe that helps already :)

**Comment by flippingbits** [comment]
> I can also try to add a "standard PEM" file to the list that in a way works like one of your baked in ones - maybe that helps already :)

It would be great if you could give that a try.

> We ship the VS Code extension with a few baked-in certs that are used to verify server certs. When a PEM file is configured, we ignore the baked-in certs at the moment. Let me see if we can change that so that we also try the baked-in certs to verify the server cert of the data plane. Maybe this will fix your issues.

FWIW, we've implemented this in https://github.com/confluentinc/ide-sidecar/pull/148 and will ship it with the upcoming `v0.21.x` release of the extension. I'll reopen the issue until you've confirmed that the fix is working for you.

**Comment by xdgrulez** [comment]
Hi Stefan,

I just tried the idea of using a standard PEM file (with about 10 which
looked like they were), but that didn't work. Still only works with the
"insecure" setting.

So looking forward to 0.21.x :)

Best, Ralph


Am Do., 7. Nov. 2024 um 20:50 Uhr schrieb Stefan Sprenger <
***@***.***>:

**Comment by flippingbits** [comment]
> Hi Stefan, I just tried the idea of using a standard PEM file (with about 10 which looked like they were), but that didn't work. Still only works with the "insecure" setting. So looking forward to 0.21.x :) Best, Ralph Am Do., 7. Nov. 2024 um 20:50 Uhr schrieb Stefan Sprenger < ***@***.***>

Thanks for giving it a try, @xdgrulez! I expect the 0.21.x release to land within the next few days and will ping you once it's available.

By the way, are you able to reach the REST endpoint of the private cluster from your browser without running into SSL-related errors?

**Comment by xdgrulez** [comment]
Hi Stefan,

good point... I do reach the REST endpoint from my Browser, yes :)

Next I looked up the certificate used by the Browser using the Chrome
Developer Console, added this to the PEM list in the VSC plugin config, and
it works like a charm :) Solved :)

Best, Ralph




Am Mo., 11. Nov. 2024 um 12:49 Uhr schrieb Stefan Sprenger <
***@***.***>:

**Comment by flippingbits** [comment]
> Hi Stefan,
> 
> good point... I do reach the REST endpoint from my Browser, yes :)
> 
> Next I looked up the certificate used by the Browser using the Chrome
> Developer Console, added this to the PEM list in the VSC plugin config, and
> it works like a charm :) Solved :)
> 
> Best, Ralph

Nice catch! 👍 Thanks for taking time to investigate the issue with me.
