### ISSUE TITLE
Increase 'upload schema' feature visibility through 'pick a file' sort of flow given a single schema registry.

### ISSUE THREAD

**Issue by jlrobins** [confluentinc/vscode#531]
1. Add a new '+' icon action in the schemas view titlebar. Will start the flow from the perspective of this schema registry, but unknown file.
2. Starts a 'Pick a file ...' sort of flow like used for picking PEM files for connection TLS certs, https://github.com/confluentinc/vscode/blob/6b14b4a853a6c50594f267ad3ec84701a1910f29/src/commands/connections.ts#L35 , but filtering for `avsc|json|proto` files.
3. Ends up calling into existing functionality for uploading said schema contents into the given schema registry.

**Comment by derek1ee** [comment]
I recommend offering a few different options after clicking the "+" button:

- Choose a file
- New JSON schema
- New AVRO schema
- New protobuf schema

Choosing "New * schema" will open an editor with blank or preferrably a basic placeholder content

**Comment by shouples** [comment]
Done as part of https://github.com/confluentinc/vscode/pull/741
