### ISSUE TITLE
Bug with local stop, partial container delete via docker, start

### ISSUE THREAD

**Issue by jlrobins** [confluentinc/vscode#588]
1. Have two brokers + schema reg running.
1. Stop them all.
1. Go to Docker and destroy the stopped schema reg container.
1. tell vscode to start both local kafka and schema registries.

Then get error popup and the schema registry never gets started:

![image](https://github.com/user-attachments/assets/832cd0a2-a8f9-44e0-9b00-066bfc219863)

**Comment by shouples** [comment]
Can't reproduce anymore after updates to the local resource start/stop flows and quickpick adjustments.
