### ISSUE TITLE
After uploading a new schema, if the target schema registry is selected, the list should be refreshed to show the new schema.

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#640]
1. Select a schema registry.
2. Open a schema.
3. Save as local file.
4. Edit the schema.
5. Upload the schema to result in a new version of the schema.
6. Observe the schema tree.

Expected: the list auto refreshes to show the newly uploaded schema.
Actual: doesn't auto refresh, requires manually refresh via the refresh button.

**Comment by shouples** [comment]
Need to at least refresh the Schemas view even if the new schema isn't "revealed" in the view
