### ISSUE TITLE
Stopping all local resources hangs if SR isn't running

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#671]
1. Start local Kafka via the extension, make sure to only start Kafka, not Schema Registry.
2. Click "Stop".
3. Use the global checkbox to check both Kafka and SR to be stopped.

Expected:
1. No op on SR since it's not running.
2. Kafka stopped

Actual:
1. Hangs at "waiting for 1 SR container to stop"

**Comment by shouples** [comment]
Marking as a duplicate since the fix will be covered by https://github.com/confluentinc/vscode/issues/536
