### ISSUE TITLE
On resource change, the list always refresh with Confluent Cloud option expanded.

### ISSUE THREAD

**Issue by derek1ee** [confluentinc/vscode#681]
1. Sign into Confluent Cloud.
2. Start Local.
3. Collapse Confluent Cloud.
4. Stop Local.

Expected:
1. Confluent Cloud subtree stays collapsed.

Actual:
1. Confluent Cloud subtree becomes expanded.

**Comment by shouples** [comment]
We should change this back to a constant prefix like `ccloud-connected` but add an extension version suffix so it doesn't break on extension updates:
https://github.com/confluentinc/vscode/blob/6cae61a39d0ef74374d0eacc0f8529d68560810f/src/viewProviders/resources.ts#L223-L224
