### ISSUE TITLE
Authentication Failed when connecting using a CC SSO user account

### ISSUE THREAD

**Issue by j3-signalroom** [confluentinc/vscode#704]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### On what operating system are you seeing the problem?

Windows (x64)

### VS Code version

Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

### Version of Confluent extension

0.21.3

### To Reproduce

1. Click on Connect to Confluent Cloud
2. The VSCode dialog box appears, and clicked the Allow button, to allow the extension to sign in to Confluent Cloud.
3. Enter my SSO email address
4. Then a web page appears with the Authentication Failed message

### Current vs. Expected behavior

I expect the login to be successful and see my CC resources in Confluent for VScode extension.

### Relevant log output

```shell
2024-12-05 09:32:34.207 [error] [errors] [browser sign-in flow] error: {"authStatus":"NO_TOKEN","connectionId":"vscode-confluent-cloud-connection"}
2024-12-05 09:32:34.218 [error] [commands.connections] error creating CCloud connection {"error":{"name":"Error","message":"Authentication failed, see browser for details"}}
2024-12-05 09:32:34.219 [error] [commands] Error invoking command "confluent.connections.create": Authentication failed, see browser for details
```

### Which area(s) are affected? (Select all that apply)

Connections, Confluent Cloud, Topics, Schemas, Messages

**Comment by flippingbits** [comment]
Hey @j3-signalroom, Thanks for reporting the issue!

Do you see any further error message on the web page with the Authentication Failed message?

**Comment by j3-signalroom** [comment]
Hi,

This is the message I get:
![image](https://github.com/user-attachments/assets/79d6e90d-4c5e-41e6-81f9-95cf32a6dc19)

**Comment by flippingbits** [comment]
@j3-signalroom, Thanks! It looks like the URI of that page contains some kind of error description. Do you mind sharing the full URI here, assuming it doesn't contain sensitive information?

**Comment by j3-signalroom** [comment]
Well it depends, if any of the URL parameter contain secure info:
```
state
client
protocol
response_type
code_challange_method
code_challenge
redirect_uri
scope
```

Please advise.

**Comment by flippingbits** [comment]
Thanks!

I meant the URL `http://127.0.0.1:26636/gateway/v1/callback-vscode-docs?error=invalid_request&error_description=the...` from your screenshot. I'd be mainly interested in the query param `error_description`.

**Comment by j3-signalroom** [comment]
Got it!

```
http://127.0.0.1:26636/gateway/v1/callback-vscode-docs?error=invalid_request&error_description=the%20connection%20was%20disabled&state=hIeUfrYoAhDB9kHFxw-jjq4yUFyomAZaVvqTzYOkpCY
```

**Comment by flippingbits** [comment]
Thanks, that's helpful!

In general, signing in via SSO works for the VS Code extension. I checked it this morning.

I'll ask our Auth team about the error message and get back to you ASAP. Thanks for your patience!

**Comment by j3-signalroom** [comment]
Yeah, I would think so too!  I appreciate your attention to the matter, and I am looking forward to hearing the feedback from the Auth Team.

**Comment by flippingbits** [comment]
Do you mind sharing the email address you're using to sign in with me? We want to confirm the SSO provider is set up correctly. You can send it to ssprenger at confluent dot io. Thanks!

**Comment by j3-signalroom** [comment]
No problem, I went ahead emailed you the email address, yesterday.

(I know you know, I am just keeping this issue dialog up to date.  ;-))

**Comment by flippingbits** [comment]
@j3-signalroom could sort out the issue offline. Somehow, the VS Code extension's OAuth app wasn't enabled for their SSO provider. We'll make sure this doesn't happen again.

**Comment by j3-signalroom** [comment]
Thank you, Stefan for being so helpful and getting it done!
